spring.application.name=My Journal

# Database configurations
spring.data.mongodb.uri=mongodb+srv://akshayu383_db_user:akakakak@cluster0.xqa1vty.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=JournalDB
spring.data.mongodb.auto-index-creation=true